trigger:
  - main
 
pool:
  name: GANA_AZUREDEVOPS
  
steps:

# ─────────────────────────────────────────
# STEP 1: pull image from Docker Hub
# ─────────────────────────────────────────
  - script: 
     docker pull nginx:mainline-alpine3.23
    displayName: "Step 1 - Pull Docker Image"

# ─────────────────────────────────────────
# STEP 2: Install CICD sensor with log level 5
# ─────────────────────────────────────────
  - script: 
    docker run -d --restart on-failure 
       -v /var/run/docker.sock:/var/run/docker.sock:ro \
       -v /etc/qualys:/usr/local/qualys/qpa/data/conf/agent-data \
       -v /usr/local/qualys/sensor/data:/usr/local/qualys/qpa/data \ 
       -e ACTIVATIONID=bc881128-fb22-47ab-bb1b-43689b371bb5 \
       -e CUSTOMERID=23a2af79-08e7-52ed-821d-ef594303be21 \
       -e POD_URL=https://cmsqagpublic.qg1.apps.qualys.com/ContainerSensor \
       --net=host \
       --name qualys-container-sensor \
       qualys/qcs-sensor:latest \
       --cicd-deployed-sensor \
       --log-level 5 \
       --perform-sca-scan

# ─────────────────────────────────────────
# STEP 4: cicd sensor installation validation
# ─────────────────────────────────────────
  - script: |
      echo "Checking Images are available (or) not"
      docker images
      displayName: "Check Docker Images"
      echo "Checking Qualys Container sensor is running (or) not "
      docker ps -a
      displayName: "check sensor is running or not"

# ─────────────────────────────────────────
# STEP 4: Scan the pulled image
# ─────────────────────────────────────────
  - script: |
      echo " Give sometime to qualys to scan the image "
      export IMAGE_ID=$(docker images --no-trunc --quiet nginx:mainline-alpine3.23)
      echo "IMAGE_ID=$IMAGE_ID"
      docker tag nginx:mainline-alpine3.23 qualys_scan_target:$IMAGE_ID
      cat /usr/local/qualys/sensor/data/logs/qpa.log
      sleep 600
      egrep -ai -n \
      'Scan started for docker image|Scan completed successfully for docker image|Upload Changelist success for docker image|Scanning
      failed for docker image' 
      /usr/local/qualys/sensor/data/logs/qpa.log
displayName: "Step 3 - Scan Docker Image"
